import os
from airflow.models import Variable


AWS_ACCESS_KEY_ID = Variable.get("AWS_ACCESS_KEY_ID_BESTSELLERS")
AWS_SECRET_ACCESS_KEY = Variable.get("AWS_SECRET_ACCESS_KEY_BESTSELLERS")
REDSHIFT_CLUSTER_IDENTIFIER = Variable.get("REDSHIFT_CLUSTER_IDENTIFIER")
DATABASE_NAME = Variable.get("DATABASE_NAME")
DATABASE_USER = Variable.get("DATABASE_USER")
